### ISSUE TITLE
Exposé

### ISSUE THREAD

**Issue by s3n-w6i** [pr0gr8mm3r/facharbeit2019#1]
Abgabe: 22.03.
Dateiaustausch: Mi, 20.03.

**Comment by s3n-w6i** [comment]
[GFS-Richtlinien](http://www.aeg-reutlingen.de/unsere-schule/profile/gfs-richtlinien/)

@pr0gr8mm3r
- [x] Deckblatt
- [x] Quellen
- [ ] Zielsetzung

**Comment by BenisTrinh** [comment]
@BenisTrinh 
- [x] Einführung
- [x] Material (Framework)
- [x] Arbeitsschritte und Zeitplanung
